# ML-02 — Research Question and Provisional Lane

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane (or freestyle) and why

*Name your lane — or say 'freestyle' and describe your own question. One short paragraph: why this one?*

###**  Chosen Lane: Refresh / Content Opportunity Scoring  **

I am choosing Lane 2: Refresh / Content Opportunity Scoring. This lane focuses on prioritizing content assets that are losing traction or becoming stale so that human editors can intervene efficiently. This direction aligns perfectly with the provided anonymized starter dataset and baseline pipeline, allowing me to focus heavily on learning how to turn raw historical performance signals into an actionable, prioritized decision-support queue rather than guessing a custom framing from scratch.

## 2. The question: decision, action, cost of a wrong call

*What decision does your work improve? Who acts on it? What does a wrong recommendation cost?*

###** Problem Framing  **

**The Core Question:**
Which high-exposure pages are showing the strongest signs of performance decay (decline in clicks, impressions, or engagement) and should be reviewed first for a content refresh?

**The Unit of Analysis:**
A single pseudonymized content item (URL/page level) per client.

**The Decision It Improves:**
It optimizes editorial resource allocation by shifting from random or strictly calendar-based content updates to an evidence-backed, high-priority review schedule.

**The Concrete Action:**
A content reviewer or editor opens the top-ranked pages in the queue, inspects the associated reason codes, and manually updates, expands, or optimizes the content.

**The Cost of a Wrong Call:**
A False Positive costs manual labor—an editor wastes valuable time reviewing a page that doesn't actually need adjustments. A False Negative costs lost revenue and traffic—a major traffic-driving page continues to silently decay without intervention.

**Why ML/Data is Needed:**
Simple heuristics (like checking age alone) ignore complex combinations of traffic momentum, search volume, and engagement signals across thousands of URLs.

## 3. Quick look at the data (2-3 real numbers)

*Load the starter CSV below and show 2-3 real numbers that make your lane look worth the next 7 weeks.*

In [6]:
import pandas as pd

# Load the small anonymized starter dataset
df = pd.read_csv('content_refresh_anonymized.csv')
# Calculate 3 real numbers to justify the project
total_rows = len(df)
declining_count = len(df[df['trend_direction'] == 'down'])
pct_declining = (declining_count / total_rows) * 100
avg_impressions = df['impressions_90d'].mean()

print(f"--- Dataset Quick Metrics ---")
print(f"1. Total content items in starter dataset: {total_rows:,}")
print(f"2. Content items currently in active decline: {declining_count:,} ({pct_declining:.2f}%)")
print(f"3. Average impressions over prior 90 days: {avg_impressions:,.2f}")

--- Dataset Quick Metrics ---
1. Total content items in starter dataset: 30,000
2. Content items currently in active decline: 16,262 (54.21%)
3. Average impressions over prior 90 days: 5,200.37


--- Dataset Quick Metrics ---
1. Total content items in starter dataset: 30,000
2. Content items currently in active decline: 16,262 (54.21%)
3. Average impressions over prior 90 days: 5,200.37

## 4. Careful words: what I can and can't claim

*Write what your work will be able to say (observed, directional, decision-support) — and what it never will (causal proof, 'predicting Google').*

###** Claims and Constraints  **

**What I CAN Claim:**
This system functions strictly as a decision-support tool. It analyzes historical, observable performance signals to rank pages based on their relative risk of traffic decay and provides structured reason codes to accelerate human audit workflows.
**What I CANNOT Claim:**
This system does not offer causal proof; I cannot guarantee that editing a highly ranked page will cause it to recover traffic. Furthermore, this analysis relies on observable search performance data and makes no claims to reverse-engineer, predict, or isolate internal Google ranking algorithm factors.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.